### ISSUE TITLE
Solution - Shaylyn Myshrall

### ISSUE THREAD

**Issue by ShaylynHM** [ShaylynHM/content-to-code#1]
@hellachella 

- 1. <body> contains the bulk of information on the web page
- 2. <h1> primary heading on the website
- 3. <time datetime="</time> for indicating readable date and time
- 4. <p> block of text separate from others 
- 5. <video poster="..." autoplay loop muted controls> for embedding videos into a website
- 6. <h2> content heading, sub-heading... But I feel like you could also use <hgroup> for same treatment.
- 7. <p> block of text separate from others
- 8. <strong> defines important text
- 9. <b> defines bold text
- 10. <em> emphasized text
- 11. <a href=""> attribute and define a link
- 12. <h2> new heading, sub-heading
- 13. <ol> ordered list - alphabetical 
- 14. <li> a single list item
- 15. <h2> a new heading
- 16. <dl> a descriptive list with terms and definitions
- 17. <dt> description title, the term of the item
- 18. <dd> description definition, the data, or the text of the item
- 19. <h2> header, new heading
- 20. <div> random content ?
- 21. <blockquote> a stand alone quote from another source
- 22. <br> created a line break significant to the content
- 23. <i> italic text
- 24. <h2> new heading
- 25. <address> defines contact information
@hellachella

**Comment by hellachella** [comment]
PS the reason why this looks all garbled is that I forgot to tell you guys that issues are html friendly which means if you put tags, they actually behave like an html document. You can wrap your tags in tilda marks if you ever need them to show as code.
